### ISSUE TITLE
Server Crash with Invalid IDs

### ISSUE THREAD

**Issue by Johann-jpg** [ishLearn/ishLearn#169]
**Describe the bug**
Der Server stürzt ab, sobald man eine schlechte ID als Query Parameter in der ULR übergibt.

**To Reproduce**
1. http://localhost:8080/#/projects/view/jasfd%C3%B6kl
2. See error

**Comment by SebastianThomas** [comment]
@Johann-jpg Backend handling working, however the frontend just stays blank.
